name: Auto-populate PR description for dev branch

on:
  pull_request:
    branches:
      - dev

jobs:
  set-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read PR template content
        id: read-template
        run: echo "::set-output name=template::$(cat .github/PULL_REQUEST_TEMPLATE/dev.md)"

      - name: Set PR description
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const template = process.env.template;
            github.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: template
            })
